/*
 * Blockmate
 *
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Blockmate.Client.OpenAPIDateConverter;

namespace Io.Blockmate.Model
{
    /// <summary>
    /// GetDomainFromAddress200ResponseMetadataAttributesInner
    /// </summary>
    [DataContract]
    public partial class GetDomainFromAddress200ResponseMetadataAttributesInner :  IEquatable<GetDomainFromAddress200ResponseMetadataAttributesInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDomainFromAddress200ResponseMetadataAttributesInner" /> class.
        /// </summary>
        /// <param name="displayType">displayType.</param>
        /// <param name="traitType">traitType.</param>
        /// <param name="value">value.</param>
        public GetDomainFromAddress200ResponseMetadataAttributesInner(string displayType = default(string), string traitType = default(string), GetDomainFromAddress200ResponseMetadataAttributesInnerValue value = default(GetDomainFromAddress200ResponseMetadataAttributesInnerValue))
        {
            this.DisplayType = displayType;
            this.TraitType = traitType;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets DisplayType
        /// </summary>
        [DataMember(Name="display_type", EmitDefaultValue=false)]
        public string DisplayType { get; set; }

        /// <summary>
        /// Gets or Sets TraitType
        /// </summary>
        [DataMember(Name="trait_type", EmitDefaultValue=false)]
        public string TraitType { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public GetDomainFromAddress200ResponseMetadataAttributesInnerValue Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDomainFromAddress200ResponseMetadataAttributesInner {\n");
            sb.Append("  DisplayType: ").Append(DisplayType).Append("\n");
            sb.Append("  TraitType: ").Append(TraitType).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetDomainFromAddress200ResponseMetadataAttributesInner);
        }

        /// <summary>
        /// Returns true if GetDomainFromAddress200ResponseMetadataAttributesInner instances are equal
        /// </summary>
        /// <param name="input">Instance of GetDomainFromAddress200ResponseMetadataAttributesInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDomainFromAddress200ResponseMetadataAttributesInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayType == input.DisplayType ||
                    (this.DisplayType != null &&
                    this.DisplayType.Equals(input.DisplayType))
                ) && 
                (
                    this.TraitType == input.TraitType ||
                    (this.TraitType != null &&
                    this.TraitType.Equals(input.TraitType))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayType != null)
                    hashCode = hashCode * 59 + this.DisplayType.GetHashCode();
                if (this.TraitType != null)
                    hashCode = hashCode * 59 + this.TraitType.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
