/*
 * Blockmate
 *
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Blockmate.Client.OpenAPIDateConverter;

namespace Io.Blockmate.Model
{
    /// <summary>
    /// NftTokenUri
    /// </summary>
    [DataContract]
    public partial class NftTokenUri :  IEquatable<NftTokenUri>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NftTokenUri" /> class.
        /// </summary>
        /// <param name="raw">String - Uri representing the location of the NFT&#39;s original metadata blob. This is a backup for you to parse when the metadata field is not automatically populated..</param>
        /// <param name="gateway">String - Public gateway uri for the raw uri above..</param>
        public NftTokenUri(string raw = default(string), string gateway = default(string))
        {
            this.Raw = raw;
            this.Gateway = gateway;
        }

        /// <summary>
        /// String - Uri representing the location of the NFT&#39;s original metadata blob. This is a backup for you to parse when the metadata field is not automatically populated.
        /// </summary>
        /// <value>String - Uri representing the location of the NFT&#39;s original metadata blob. This is a backup for you to parse when the metadata field is not automatically populated.</value>
        [DataMember(Name="raw", EmitDefaultValue=false)]
        public string Raw { get; set; }

        /// <summary>
        /// String - Public gateway uri for the raw uri above.
        /// </summary>
        /// <value>String - Public gateway uri for the raw uri above.</value>
        [DataMember(Name="gateway", EmitDefaultValue=false)]
        public string Gateway { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NftTokenUri {\n");
            sb.Append("  Raw: ").Append(Raw).Append("\n");
            sb.Append("  Gateway: ").Append(Gateway).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NftTokenUri);
        }

        /// <summary>
        /// Returns true if NftTokenUri instances are equal
        /// </summary>
        /// <param name="input">Instance of NftTokenUri to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NftTokenUri input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Raw == input.Raw ||
                    (this.Raw != null &&
                    this.Raw.Equals(input.Raw))
                ) && 
                (
                    this.Gateway == input.Gateway ||
                    (this.Gateway != null &&
                    this.Gateway.Equals(input.Gateway))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Raw != null)
                    hashCode = hashCode * 59 + this.Raw.GetHashCode();
                if (this.Gateway != null)
                    hashCode = hashCode * 59 + this.Gateway.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
